### ISSUE TITLE
Which Bord to select?

### ISSUE THREAD

**Issue by BrookeDot** [mrjohnk/TinyGlo#1]
Hi there, 

Which board or driver needs to be installed to program the TinyGlo+ ?

**Comment by mrjohnk** [comment]
Below is a link to the source code of the demo Arduino sketch that ships
with each unit as well as a schematic of the board design:
https://github.com/mrjohnk/TinyGlo2

To be able to upload your own Arduino sketches, be sure to follow the
directions on the page linked below to get your Arduino software ready to
upload. TinyGlo+ is based upon the Digispark Pro design, so they behave
similarly.
http://digistump.com/wiki/digispark/tutorials/connectingpro

**Comment by BrookeDot** [comment]
Thanks John, I'll go ahead and close this.
